name: CI

on: [push]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set execution policy
      run: Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process
      shell: powershell

    - name: Add fusesoc library and create Vivado project
      run: D:\Xilinx\Vivado\2022.1\settings64.bat && cd jtag_to_axi_master/fpga && fusesoc library add jtag_to_axi_master . && fusesoc run --build-root ../../../../../../ --no-export --target project --setup --build f:yunus:jtag_to_axi_master --jobs=6
      shell: cmd
