name: CI

on: [push]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set execution policy
      run: Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process
      shell: powershell


    - name: Move bit file to artifacts
      run: mkdir artifacts && copy ..\..\..\..\f_yunus_jtag_to_axi_master_0\project-vivado\f_yunus_jtag_to_axi_master_0.runs\impl_1\design_1_wrapper.bit artifacts\ && copy ..\..\..\..\f_yunus_jtag_to_axi_master_0\project-vivado\f_yunus_jtag_to_axi_master_0.runs\impl_1\design_1_wrapper.ltx artifacts\
      shell: cmd

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: vivado-artifacts
        path: artifacts/design_1_wrapper.bit
