name: Build and Source Vivado

on:
  push:
    branches:
      - deneme  # Adjust this if you're using a different branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./docker
        file: ./docker/Dockerfile
        push: false  # Set to true if you want to push to a registry
        tags: vivado:2022.1

    - name: Run Vivado inside Docker container
      run: |
        docker run --rm vivado:2022.1 /bin/bash -c "source /opt/Xilinx/Vivado/2022.1/settings64.sh && vivado -version"
