name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Vivado environment
      run: |
        call "D:\Xilinx\Vivado\2022.1\settings64.bat"
      
    - name: Run build script
      run: |
        ./build-script.sh
